### ISSUE TITLE
Issue 5 for Milestone 2: Preprocessing and Data Transformation (Lab 3 and 4)

### ISSUE THREAD

**Issue by Bernard-Otieno** [Bernard-Otieno/laravel#8]
- [x] Confirmation of the presence of missing values
- [ ] Data imputation (if applicable)
- [x] Data transformation (if applicable)
