### ISSUE TITLE
 Issue 6 for Milestone 3: Training the Model (Lab 5-8)

### ISSUE THREAD

**Issue by Bernard-Otieno** [Bernard-Otieno/laravel#9]
- [x] Data splitting
- [ ] Bootstrapping
- [x] Cross validation (basic, repeated, or LOOCV)
- [x] Model training for either classification, regression, association, or clustering (as applicable)
- [x] Model performance comparison using resamples (for classification and regression)

**Comment by Bernard-Otieno** [comment]
Bootstrapping not necessary 
<img width="960" alt="image" src="https://github.com/Bernard-Otieno/laravel/assets/107553854/011b0bc5-51b7-43d4-ab27-7ed94e0c4ec4">
